name: Sonar tests

on: 
  push:
    branches: [ master, sonar-test, tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JAVA 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
      env: 
        GITHUB_ACTOR: ${{github.actor}}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build with Maven
      env:
        GITHUB_ACTOR: ${{github.actor}}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        cat $GITHUB_WORKSPACE/settings.xml
        mvn package -s $GITHUB_WORKSPACE/settings.xml

    # - name: Teste Sonar
    #   run: mvn sonar:sonar
    #       -Dsonar.host.url=${{ secrets.SONAR_URL }}
    #       -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}-${GITHUB_REF##*/}
    #       -Dsonar.projectName=${{ secrets.SONAR_PROJECT_KEY }}-${GITHUB_REF##*/}
    #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    #       -Dsonar.verbose=true
    #       -Dsonar.tests=src/test
