name: Sonar tests

on:
  pull_request:
    branches: [ master, sonar-test, tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JAVA 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn package -DskipTests

    - name: Teste Sonar
      run: mvn sonar:sonar
          -Dsonar.host.url=${{ secrets.SONAR_URL }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.verbose=true
          -Dsonar.tests=src/test 
